"""
Real-time whiteboard analysis agent using LangChain + Google Gemini.

Input
-----
Plain-text ``visual_delta`` strings produced by an upstream visual pipeline:

    live image feed → frame filter → Gemini Vision → change description → visual_delta

The agent never receives raw images or audio — only the text output of that
pipeline passed here via ``process_frame(visual_delta, timestamp_ms)``.

Model
-----
Google Gemini 2.5 Flash Lite via ``langchain-google-genai``.
"""

from __future__ import annotations

import os
from typing import Any

from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage  # noqa: F401
from langchain_core.tools import tool
from langchain_google_genai import ChatGoogleGenerativeAI

from core.graph import SystemDesignGraph

# ------------------------------------------------------------------ #
# System prompt                                                        #
# ------------------------------------------------------------------ #

SYSTEM_PROMPT = """\
You are a real-time system design analysis agent. You receive plain-text
visual_delta updates generated by an upstream pipeline:

live image feed → valid frames with changes → Gemini Vision → change description →
visual_delta

Your job is to maintain an accurate graph representation of the system design
the user is building.  The graph is your source of truth.  Every time you
receive a visual_delta update, determine what structural change it describes
and call the appropriate graph mutation tool.

Available tools
---------------
- create_node(id, label, type)
    Call when a new component appears (box drawn, label written, etc.).
    Valid types: service, database, cache, load_balancer, queue, client,
    storage, external.

- add_details_to_node(id, details)
    Call when the user annotates an existing component with extra information
    (technology stack, role, scaling notes, etc.).

- delete_node(id)
    Call when a component is erased.

- add_edge(from_id, to_id, label)
    Call when an arrow is drawn between two components.

- remove_edge(from_id, to_id)
    Call when an arrow is erased or redirected.

- set_entry_point(id)
    Call as soon as you identify the user-facing entry point of the system
    (Browser, Mobile App, CDN, etc.).  Do this early.

- insert_node_between(from_id, new_id, new_label, new_type, to_id, ...)
    Call when a new component is inserted between two already-connected nodes.
    Atomically removes the old edge and creates two new ones.

- get_graph_state()
    Call to inspect the current graph before making structural decisions that
    depend on existing topology.

Decision rules
--------------
1. Only call a tool when you have sufficient confidence that a structural change
   was intended.  Do not add nodes for vague, incomplete, or ambiguous sketches.
2. You may call multiple tools in one turn if the delta describes multiple
   changes.
3. If the delta describes no new changes, do not call any tools.
4. Never fabricate nodes or edges.  Every mutation must be grounded in the
   visual_delta text you received.

Input format
------------
{
  "visual_delta": "<text description of what changed on the whiteboard>",
  "current_timestamp": <milliseconds since session start>
}

Response format
---------------
After any tool calls, produce exactly one sentence spoken aloud to the user —
either confirming what you understood or asking a clarifying question.
"""

# ------------------------------------------------------------------ #
# LangChain tool factory                                               #
# ------------------------------------------------------------------ #


def _build_tools(graph: SystemDesignGraph) -> list[Any]:
    """
    Create LangChain @tool functions that mutate the shared graph instance.
    """

    @tool
    def create_node(id: str, label: str, type: str) -> dict:  # noqa: A002
        """Register a new system component on the graph when it appears on the whiteboard.

        Args:
            id: Unique snake_case identifier (e.g. 'api_gateway').
            label: Human-readable name as drawn (e.g. 'API Gateway').
            type: One of: service, database, cache, load_balancer, queue,
                  client, storage, external.
        """
        node = graph.create_node(id=id, label=label, type=type)
        return {"status": "created", "node": {"id": node.id, "label": node.label, "type": node.type}}

    @tool
    def add_details_to_node(id: str, details: dict) -> dict:  # noqa: A002
        """Add descriptive details to an existing node.

        Args:
            id: ID of the node to annotate.
            details: Key-value pairs
                (e.g. {"technology": "PostgreSQL", "role": "primary write store"}).
        """
        node = graph.add_details_to_node(id=id, details=details)
        return {"status": "updated", "node": {"id": node.id, "details": node.details}}

    @tool
    def delete_node(id: str) -> dict:  # noqa: A002
        """Remove a component and all its edges when it is erased from the whiteboard.

        Args:
            id: ID of the node to delete.
        """
        graph.delete_node(id=id)
        return {"status": "deleted", "id": id}

    @tool
    def add_edge(from_id: str, to_id: str, label: str | None = "") -> dict:
        """Create a directed connection between two components when an arrow is drawn.

        Args:
            from_id: Source node ID.
            to_id: Destination node ID.
            label: Optional relationship label
                (e.g. 'routes traffic to', 'writes to', 'publishes events').
        """
        edge = graph.add_edge(from_id=from_id, to_id=to_id, label=label or "")
        return {"status": "added", "edge": {"from": edge.from_id, "to": edge.to_id, "label": edge.label}}

    @tool
    def remove_edge(from_id: str, to_id: str) -> dict:
        """Remove a directed connection when an arrow is erased.

        Args:
            from_id: Source node ID.
            to_id: Destination node ID.
        """
        graph.remove_edge(from_id=from_id, to_id=to_id)
        return {"status": "removed", "from": from_id, "to": to_id}

    @tool
    def set_entry_point(id: str) -> dict:  # noqa: A002
        """Designate the logical entry point of the system (user-facing start).
        Call this as soon as you identify it.

        Args:
            id: ID of the entry-point node (e.g. 'browser', 'mobile_app', 'cdn').
        """
        graph.set_entry_point(id=id)
        return {"status": "entry_point_set", "entry_point": id}

    @tool
    def insert_node_between(
        from_id: str,
        new_id: str,
        new_label: str,
        new_type: str,
        to_id: str,
        from_label: str = "",
        to_label: str = "",
    ) -> dict:
        """Insert a new node between two already-connected nodes.

        Removes the direct edge from_id→to_id and creates two new edges:
        from_id→new_id and new_id→to_id.

        Args:
            from_id: ID of the upstream node.
            new_id: Unique ID for the new node.
            new_label: Human-readable label for the new node.
            new_type: Component type for the new node.
            to_id: ID of the downstream node.
            from_label: Optional label for the upstream edge.
            to_label: Optional label for the downstream edge.
        """
        node = graph.insert_node_between(
            from_id=from_id,
            new_id=new_id,
            new_label=new_label,
            new_type=new_type,
            to_id=to_id,
            from_label=from_label,
            to_label=to_label,
        )
        return {"status": "inserted", "node": {"id": node.id, "label": node.label, "type": node.type}}

    @tool
    def get_graph_state() -> dict:
        """Return the full current state of the graph (all nodes and edges).
        Call this to verify your understanding before structural decisions.
        """
        return graph.get_state()

    return [
        create_node,
        add_details_to_node,
        delete_node,
        add_edge,
        remove_edge,
        set_entry_point,
        insert_node_between,
        get_graph_state,
    ]


# ------------------------------------------------------------------ #
# Agent                                                                #
# ------------------------------------------------------------------ #


class WhiteboardAgent:
    """
    Stateful LangChain agent for real-time whiteboard analysis.

    One instance lives for the lifetime of a session. Conversation history
    persists across frames so the model maintains context between snapshots.
    """

    def __init__(self, graph: SystemDesignGraph) -> None:
        self.graph = graph
        self.llm = ChatGoogleGenerativeAI(
            model="gemini-2.5-flash-lite",
            temperature=0,
            google_api_key=os.environ.get("GOOGLE_API_KEY", ""),
        )
        self.tools = _build_tools(graph)
        self.llm_with_tools = self.llm.bind_tools(self.tools)
        self.tool_map: dict[str, Any] = {t.name: t for t in self.tools}

        # Conversation history persists across all frames in a session.
        self.message_history: list = [SystemMessage(content=SYSTEM_PROMPT)]

    # ------------------------------------------------------------------ #
    # Public interface                                                     #
    # ------------------------------------------------------------------ #

    def process_frame(self, visual_delta: str, timestamp_ms: int) -> str:
        """
        Process a visual_delta description and apply graph mutations.

        The visual_delta is produced upstream by the visual pipeline
        (frame filter → OCR → change description). This method never
        receives raw images.

        Args:
            visual_delta: Plain-English description of what changed on the
                          whiteboard (e.g. "A box labeled 'API Gateway' was
                          drawn with an arrow to 'Database'").
            timestamp_ms: Milliseconds since session start.

        Returns:
            One-sentence verbal response suitable for TTS output.
        """
        human_msg = HumanMessage(
            content=(
                f'{{"visual_delta": {visual_delta!r}, "current_timestamp": {timestamp_ms}}}\n\n'
                "Call the appropriate graph tools for any structural changes, "
                "then respond with a single sentence."
            )
        )

        self.message_history.append(human_msg)

        # Agentic loop: keep invoking until the model stops requesting tool calls.
        while True:
            response = self.llm_with_tools.invoke(self.message_history)
            self.message_history.append(response)

            if not response.tool_calls:
                return response.content or "I'm watching the board — keep going."

            # Execute every tool call and feed results back into the conversation.
            tool_messages: list[ToolMessage] = []
            for call in response.tool_calls:
                fn = self.tool_map.get(call["name"])
                if fn is None:
                    continue
                result = fn.invoke(call["args"])
                tool_messages.append(
                    ToolMessage(
                        name=call["name"],
                        content=str(result),
                        tool_call_id=call["id"],
                    )
                )

            self.message_history.extend(tool_messages)
            # Loop: let the model see the tool results and decide next action.

    def reset(self) -> None:
        """Clear conversation history for a new session."""
        self.message_history = [SystemMessage(content=SYSTEM_PROMPT)]
